### ISSUE TITLE
Failing localization

### ISSUE THREAD

**Issue by fjacobi** [teaminmedias-pluswerk/ke_search#28]
Since updating to ke_search 2.x we have localization errors.
I.e. all localization happening in the pi modules, like sorting and pagination links are getting wrong/no values at all. 

Any hints on how to fix that?

**Comment by fjacobi** [comment]
I debugged it today and pi2 and pi3 are missing the locallang from pi1.

I hotfixed it for me with the following:

``` php
        // hotfix for failing localization in pi2 and pi3 START
        $tmpLL = \TYPO3\CMS\Core\Utility\GeneralUtility::readLLfile('EXT:ke_search/pi1/locallang.xml', $this->LLkey);

        if(is_array($tmpLL)) {
            $this->LOCAL_LANG = array_merge_recursive(
                $tmpLL,
                ( is_array($this->LOCAL_LANG) ? $this->LOCAL_LANG : [] )
            );
        }
        // hotfix for failing localization in pi2 and pi3 END
```

in pi2 and pi3.
But not sure if that is really the best way to do it. But it works for now.

**Comment by christianbltr** [comment]
Fixed in master.

```
// use pi1 locallang values, since all the frontend locallang values for
// pi1, pi2 and pi3 are set in pi1 language file
$this->pi_loadLL('EXT:ke_search/pi1/locallang.xml');
```

**Comment by timofo** [comment]
I have updated to 2.2.0
But i get the same wrong label as with 2.1.0.
https://gyazo.com/8c8e325641841f7efdfb08ccf9afb8a3
This a link to a screenshot. "Suche" instead of "Nächste". 
Can u please helpe me?

An other question... Now the result list is a HTML list. But this is useless because i cant change the class vor the ul for example. So when i am using bootstrap framework, i cant give the ul a class. So there is no way of styling it with a framework. 
Is there a way to change the rendering from this list?

**Comment by fjacobi** [comment]
I can confirm that this is still an issue (TYPO3 6.2.21, ke_search 2.2.0)

@timofo You have to change the fluid templates.

**Comment by timofo** [comment]
Thank you for confirming the label issue.  

@fjacobi It is not possible to style it through templates. It is hard coded. 
But i hope that this will come in the future #22

**Comment by christianbltr** [comment]
@timofo 
Is a class really necessary? Can't you set a styling for the `<ul>` tag in the pagebrowser with `.kesearch_pagebrowser ul` ?

On my test environment there's a label rendered for the pagebrowser ("nächste" which is the default german translated label).

`<ul><li><a href="index.php?id=2&amp;L=1&amp;tx_kesearch_pi1%5Bsword%5D=&amp;tx_kesearch_pi1%5Bpage%5D=1&amp;tx_kesearch_pi1%5BresetFilters%5D=0&amp;tx_kesearch_pi1%5BsortByField%5D=&amp;tx_kesearch_pi1%5BsortByDir%5D=&amp;tx_kesearch_pi1%5Bfilter%5D%5B1%5D=" class="current">1</a></li> <li><a href="index.php?id=2&amp;L=1&amp;tx_kesearch_pi1%5Bsword%5D=&amp;tx_kesearch_pi1%5Bpage%5D=2&amp;tx_kesearch_pi1%5BresetFilters%5D=0&amp;tx_kesearch_pi1%5BsortByField%5D=&amp;tx_kesearch_pi1%5BsortByDir%5D=&amp;tx_kesearch_pi1%5Bfilter%5D%5B1%5D=">2</a></li> <li><a href="index.php?id=2&amp;id=2&amp;L=1&amp;tx_kesearch_pi1%5Bsword%5D=&amp;tx_kesearch_pi1%5Bpage%5D=2&amp;tx_kesearch_pi1%5BresetFilters%5D=0&amp;tx_kesearch_pi1%5BsortByField%5D=&amp;tx_kesearch_pi1%5BsortByDir%5D=&amp;tx_kesearch_pi1%5Bfilter%5D%5B1%5D=" class="next">nächste</a></li></ul>`

**Comment by timofo** [comment]
Sure it is possible to style the pagebrowser this way. But the intention of a framework like bootstrap is that u dont need to style things this way. You give your tags a class and the styling is part of the framework.
